# Работа с ошибками в программировании

## Источники ошибок в коде

1. Разработчик что-то не учёл в своём коде
2. Некая внешняя среда,  привела к возникновению ошибки
3. Сторонние библиотеки, либо код написанный не данным разработчиком.

## Сценарии взаимодействия с ошибками

### Сценарий 1

Программа не может корректно обработать ошибку и вылетает

### Сценарий 2

Программа перехватывает ошибку и корректно на неё реагирует и не вылетает

**Отказоустойчивые приложения** — приложения, которые при возникновении некритичных ошибок могут продолжать свою работу.

## Оповещения об ошибках

### Подход 1

Использование кодов ошибки. Данный подход характерен для языка Си

**Код ошибки** — целочисленный код, указывающий на причину ошибки. Для разных приложений — разные коды ошибок.

Для функции или метода выбирается определённое значение, которое не входит в область значений этой функции:

```
    public static long getFileSize(File file)
    {
        if(!file.exists()){
            return -1;
        }
        return file.length();
    }
```

**-1** — это ошибка, поскольку файлов с отрицательным размером существовать не может и тут значение ошибки не входит в область возможных возвращаемых функцией значений.

### Подход 2

```
public static int divide(int a1, int a2){
    if(a2==0){
        return -1;
    }
    return a1/a2;
}
```
Проблема в том, что если поделить 5 на -5, то вернется значение -1, как и при деление на ноль.

## Недостатки кодов ошибок
1. Код ошибки невозможно отличить от результата
2. Разработчик может забыть, что означает тот или иной цифровой код ошибки.
3. Некоторые ошибки обязательны для обработки, например нет доступа к ресурсу иначе программа вылетит.
4. Нет детальной информации у ошибки, нет трейслога.

# Исключения

**Исключения** — это специальный тип объектов, которые создаются при возникновении ошибочной ситуации и выбрасываются Java-машиной.

В случае с кодом деления на ноль в яве выведется исключение:

```
Exception in thhread "main" java.lang.ArithmeticException: / by zero
            at MainClass.main(MainClass.java:4)
```
- ошибка возникла в потоке main;
- было брошено исключение, имеющее тип java.lang.ArithmeticException, который указывает на ошибку при выполнении арифметической операции;
- есть уточняющее сообщение, о делении на 0, и далее прописано имя класса и метода, а также строка, где возникла эта ошибка.

## Подробнее про исключения

```
public class MainClass {
    public static void main(String[] args){
        int a = 0;
        int b = 10 / a;
    }
}
```

1. Итак, в строке 4 возникает попытка деления на ноль.
2. В этот момент исполняющая среда Java приостанавливает работу программы, поскольку целочисленное деление на ноль недопустимо.
3. Затем JVM формирует объект типа ArithmeticException, который служит исключением, и выполняет так называемый бросок этого объекта, чтобы в случае необходимости мы могли его перехватить и обработать.
4. В нашем простом коде никакой обработки нет, поэтому объект летит и долетает до стандартного обработчика исключений Java-машины.

Если исключение перехватывает не вашим кодом, а стандартным обработчиком, то стандартный обработчик останавливает работу
приложения целиком и выводит в консоль сообщение об исключении.

```
public class MainApp {
    public static void main(String[] args) {
        methodA();
    }

    public static void methodA(){
        methodB();
    }

    public static void methodB(){
        int[] arr = new int[10];
        System.out.println(arr[100]);
    }
}
```

Операцию невозможно выполнить, так как мы не можем взять сотый элемент, если у нас их всего 10, будет брошено исключение:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 100 out of bounds for length 10
        at com.example.MainApp.methodB(MainApp.java:14)
        at com.example.MainApp.methodA(MainApp.java:9)
        at com.example.MainApp.main(MainApp.java:5)
```
- **Exception** - возникло исключение
- **thread "main"** - в потоке main
- **java.lang.ArrayIndexOutOfBoundsException** - тип исключения ArrayIndexOutOfBoundsException (выход за пределы массива)
- Index 100 out of bounds for length 10 - это message (детальное сообщение)
- at com.example.MainApp.methodB(MainApp.java:14) - строка в которой возникло исключение
- at com.example.MainApp.main(MainApp.java:5) - начало цепочки (стека) вызовов

глядя на верхнюю строку стека вывода, сразу сможете найти причину ошибки и идя по стеку сверху вниз пройдём от места ошибки к началу всей цепочки вызовов методов.

## Намеренный проброс исключений

Код с делением на ноль можно переписать, так чтобы он выбрасывал исключение, которы мы хотим по условию:

```
public static int div(int a, int b){
    if(b==0){
        throw new RuntimeException("Нельзя делить на 0");
    }
    return a / b;
}
```

Если в коде две ошибки способные вызвать исключения, то выполнение остановится на первом и программа завершится. Поэтому никогда не возникнет ситуация с выбрасыванием одновременно нескольких исключений.